version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lab-dyn-dns"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-95h1njc4ufav"
s3_prefix = "lab-dyn-dns"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
